### ISSUE TITLE
New changes

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#10]
Check my Fork, I have added alternative methods for SSDT-SLPB_STA0B.
Tested and modified addresses of some SSDTs, for example SSDT-ALSD before it was under _SB and INI method, now under \ removed INI method.
Besides these other minor changes.
Everything I have entered and edited has been tested.
Thanks as always.

EDIT: I have ioreg of the tests done, in case you want proof.

**Comment by 5T33Z0** [comment]
Thanks. I will check it later. I have been busy. Update OCAT if you haven't already and check the QUIRKS Sectiions. You'll  be surprised!

**Comment by Baio1977** [comment]
I just updated, I see the news, I like them, it is always easier to hack

**Comment by 5T33Z0** [comment]
XSPI:

In IOReg without it:
![Bildschirmfoto 2021-12-12 um 18 59 53](https://user-images.githubusercontent.com/76865553/145724134-2e80e180-5865-4da3-a028-7c264cb7c3ea.png)

With the SSDT:

![XSPI present](https://user-images.githubusercontent.com/76865553/145724178-e3a898a8-8a60-471b-909e-77e6a7dc6df9.png)
