### ISSUE TITLE
RX 580 Users: can you select Orinoco Framebufffer in macOS Ventura?

### ISSUE THREAD

**Issue by brousseau6933** [5T33Z0/OC-Little-Translated#103]
Hello... and sorry to ask you the same question you asked in Reddit two years ago ( https://www.reddit.com/r/hackintosh/comments/vv1i4g/rx_580_users_can_you_select_orinoco_framebufffer/ ).

Still no ideas yet on your side?

Working fine, as you may know, prior to Ventura...

Thanks for your work BTW, I've implemented low power PowerPlay tables for my Sapphire RX580 successfully following your docs.

Patrice

**Comment by 5T33Z0** [comment]
I have been banned from this reddit, so I couldn't respond.

Besides [using device properties](https://github.com/5T33Z0/OC-Little-Translated/tree/main/11_Graphics/GPU/AMD_Radeon_Tweaks#config-edits), I don't know another way.

How did you verify that the framebuffer is not used?

**Comment by brousseau6933** [comment]
Hello,

I’ve checked with IORegistry Explorer and it’s easy for me to see it: I have a partition with Big Sur and Orinoco is injected properly (via devices properties) but as soon as I go back to Ventura, the generic AmdFramebuffer is used.

I thought you had found (maybe) the « why ». A bug on the Apple side? On the OpenCore side?

I use 0.8.8 No ACPI to not disturb my Windows boot and didn’t tried a more recent OC build or latest Clover though…

Thanks for your support anyway.

**Comment by brousseau6933** [comment]
I know you closed it but anyway: no difference with OC 0.9.7...

**Comment by 5T33Z0** [comment]
Maybe you have to inject the property via SSDT instead. It has an entry for Orinoco in it: https://github.com/5T33Z0/OC-Little-Translated/blob/main/11_Graphics/GPU/AMD_Radeon_Tweaks/mattystonnie/SSDT-RX580.dsl

**Comment by 5T33Z0** [comment]
I just saw this on the [Whatvergreen](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Radeon.en.md) repo

> When should I use a named framebuffer?
> 
> Named framebuffers (Baladi, Futomaki, Lotus, etc.), enabled by "Clover GPU injection" or any other methods should never ever be used. This way of GPU injection is a common mistake, preventing automatic configuration of various important GPU parameters. This will inavoidably lead to borked GPU functioning in quite a number of cases.

**Comment by brousseau6933** [comment]
> Maybe you have to inject the property via SSDT instead. It has an entry for Orinoco in it: https://github.com/5T33Z0/OC-Little-Translated/blob/main/11_Graphics/GPU/AMD_Radeon_Tweaks/mattystonnie/SSDT-RX580.dsl

Already tried with a similar SSDT, no go!

**Comment by brousseau6933** [comment]
> I just saw this on the [Whatvergreen](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Radeon.en.md) repo
> 
> > When should I use a named framebuffer?
> > Named framebuffers (Baladi, Futomaki, Lotus, etc.), enabled by "Clover GPU injection" or any other methods should never ever be used. This way of GPU injection is a common mistake, preventing automatic configuration of various important GPU parameters. This will inavoidably lead to borked GPU functioning in quite a number of cases.

Well, it works as is so, let it be then… Thanks again!

**Comment by brousseau6933** [comment]
Just to complete:

Tried my HP RX5500 instead with ATY,Boa as device properties and it worked. Performance is a tad lower than the Sapphire Pulse RX580 but this hack is used as a basic desktop computer so, doesn't matter. Power consumption is way lower too.
