### ISSUE TITLE
Apple DriverKit

### ISSUE THREAD

**Issue by Terminalstrip** [5T33Z0/OC-Little-Translated#106]
Hi sorry for writing here but I don't know how else I can contact you. Your guide works wonderfully, I just have one doubt that I can't resolve. I don't understand why the new drivers in Apple DriverKit format don't work on hackintosh, specifically I have an RME sound card that works wonderfully with the legacy drivers, but if I install the new drivers in DriverKit format they don't work. What did I miss?

**Comment by 5T33Z0** [comment]
Hi. Which OS are you using and which RME Interface are yoz referring to? Provide a product link please.

**Comment by Terminalstrip** [comment]
hdspe MADi, my system is a Haswell with Sonoma 14.3

**Comment by Terminalstrip** [comment]
hdspe MADi, my system is a Haswell with Sonoma 14.3

same history with new Dk driver of my lynx aes16 card

NEW DK driver https://www.lynxstudio.com/downloads/aes16e/macos-core-audio-driver-v2-build-10-for-pcie-and-thunderbolt/ (not see the card)

OLD Kernel Driver https://www.lynxstudio.com/downloads/aes16e/macos-core-audio-driver-build-62-for-pcie-and-thunderbolt/ (work perfect)

**Comment by 5T33Z0** [comment]
Have you installed the latest firmware update already? https://www.lynxstudio.com/downloads/aes16e/lynxfirmware-updater/

**Comment by Terminalstrip** [comment]
Yes!

**Comment by 5T33Z0** [comment]
Is `com.lynxstudio.audio.extension.dext` present in Library/SystemExtensions

Did you grant the system access to the driver in the system settings ("Allow" in gatekeeper) after installing it?

**Comment by Terminalstrip** [comment]
Yes and yes, the installation in fine, but when I reboot the app cannot see the card...

**Comment by 5T33Z0** [comment]
Have you disabled SIP in OpenCore?

**Comment by Terminalstrip** [comment]
Yes, Do you think it could have something to do with AMFI?

**Comment by 5T33Z0** [comment]
Maybe, yes. If you can, change csractiveconfig back to `00000000`, so AMFI works.

My guess is that you cannot grant the system access to the device if amfi is not working.

If you require SIP to be disabled in boot, you could add AMFIPass.kext. Eplanation: https://github.com/5T33Z0/OC-Little-Translated/blob/main/13_Peripherals/Fixing_Peripherals.md

**Comment by Terminalstrip** [comment]
With the command systemextensionsctl list I see the driver are loaded

--- com.apple.system_extension.driver_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	M3FXK28JC9	com.lynxstudio.audio.extension (2.0/10)	com.lynxstudio.audio.extension	[activated enabled]
***@***.*** ~ % 

But the Mixer.app and also the System cannot see the card….
I think this is a driver bug…or another mixer.app side thing.
Anyway that for your support, I will use the old kext driver

**Comment by 5T33Z0** [comment]
It's not about  the driver being loaded, it's about granting acess to the hardware.

I am closing this issue since it has absolutely nothing to do with OC-Little. The only reason I tried to help you was because I am an audio guy as well.

Good luck.

**Comment by Terminalstrip** [comment]
sure, if you prefer, just cancel. Thanks again
