### ISSUE TITLE
"-radvesa" flag does not work for Sonoma install, but "-amd_no_dgpu_accel" works

### ISSUE THREAD

**Issue by BillDH2k** [5T33Z0/OC-Little-Translated#107]
I've followed your excellent guide "Installing macOS Ventura or newer on Ivy Bridge systems" and successfully installed Sonoma on HP Z420/Z620 (X79 platform). One thing I've discovered was that "-radvesa" flag did not work, Sonoma install would stuck not passing this line:

(system) <warning>: failed lookup: name = com.apple.dock.fullscreen, requestor = Installer Program[59], error = 3; No such process

But "-amd_no_dgpu_accel" flag worked.  I've tested three different cards, AMD RX380, RX480, and RX580, all same results.

May be you should add a note in your guide, by suggesting "-amd_no_dgpu_accel" flag, for discrete AMD cards.

Thanks!

**Comment by 5T33Z0** [comment]
Thanks for the feedback. I will update the guide. According to the whatevergreen repo, `radvesa` supposedly "Disables ATI/AMD video acceleration completely".  Maybe it doesn't work with Sonoma.
