### ISSUE TITLE
SSDT-FACP Patch  - In system preference, battery on or off.

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#111]
A user submitted a pullrequest in my X1 Tablet's github.
I attach the link so you can evaluate whether to integrate this information and where.
https://github.com/Baio1977/Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r/pull/2

Original discussion
https://github.com/Xiashangning/BigSurface/issues/93

Having made the Tablet I thought that the NUC8 suffers from the opposite problem, it sees the battery in system preferences, but in the end it is a Mini PC Desktop and therefore I redid the patch for NUC8 and eliminated the problem.

Excuse my English, I use the translator.
Thank you

Patch X1 Tablet Batt ON in system preference
![Screenshot 2024-04-04 alle 19 44 28](https://github.com/5T33Z0/OC-Little-Translated/assets/59058746/b824d991-a6bb-4f98-95ef-29a306048f7f)
![Screenshot 2024-04-04 alle 19 49 56](https://github.com/5T33Z0/OC-Little-Translated/assets/59058746/c5796f7a-6818-435b-ac18-232ff375c370)

Patch NUC8i7HVK Batt OFF in system preference
![Screenshot 2024-04-04 alle 19 45 10](https://github.com/5T33Z0/OC-Little-Translated/assets/59058746/8ff25640-5818-4ca7-914c-a4234d1bc484)
![318968921-2485dc9e-6061-49df-a77a-eb8207f60dce](https://github.com/5T33Z0/OC-Little-Translated/assets/59058746/e613d77d-b3c8-40b8-8901-6876783ea653)

SSDT FACP a comparison:
![Screenshot 2024-04-04 alle 20 25 23](https://github.com/5T33Z0/OC-Little-Translated/assets/59058746/40ab3a21-eb9d-435f-ab8e-10ee71d65412)

**Comment by 5T33Z0** [comment]
Interesting. I will add it to the repo once I have figured out the best section to put it in.

**Comment by 5T33Z0** [comment]
I've added a sub-category for NUC fixes and posted your fix there: https://github.com/5T33Z0/OC-Little-Translated/blob/main/05_Laptop-specific_Patches/Battery_Patches/v_NUC/README.md
