### ISSUE TITLE
Patch WiFi on the fly when doing a fresh install with macOS Sonoma

### ISSUE THREAD

**Issue by gorouflex** [5T33Z0/OC-Little-Translated#113]
For those users who don’t want to mess up their WiFi card patch and do not want to prepare the OCLP app before installing macOS Sonoma, there is a solution for this

Link: https://github.com/AppleOSX/PatchSonomaWiFiOnTheFly
I cannot create the PRs because I don’t know which section to put them (guide) in

**Comment by 5T33Z0** [comment]
Interesting. Thanks for sharing. I will place it somewhere OCLP Wintel Section on the weekend
