### ISSUE TITLE
Incorrect kernel patch under CMOS Reset Fix

### ISSUE THREAD

**Issue by unitedastronomer** [5T33Z0/OC-Little-Translated#114]
The kernel -> patch mentioned [here](https://github.com/5T33Z0/OC-Little-Translated/tree/main/06_CMOS-related_Fixes/CMOS_Reset_Fix#method-1-using-a-kext-and-a-kernel-patch) is used for enabling Broadcom Ethernet under Catalina and older.

`__ZN11BCM5701Enet14getAdapterInfoEv`

**Comment by 5T33Z0** [comment]
Fixed info. Thanks.
