### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by rrt225645** [5T33Z0/OC-Little-Translated#117]
Hi,

I've followed your guide and managed to install and boot sonoma 14.5 on my x79 motherboard and 3930k cpu. The GPU ZOTAC GTX 680 4gb is not working well and getting hot as soon i just stay at the desktop not doing anything which is very strange.

i used OCLP 1.5.0 to patch the gpu and it went well but i still have this problem and not sure what is causing it.

Im still on macos 10.11.6 and have tried every macos since then and still cant have it working well as el capitan does with my hardware at least with clover bootloader...

Now im using opencore for el capitan as well and both cpu and gpu is not working well so im stuck here with my problems and its driving me nuts :(

Please i need your help since you are the only one that know what he is talking about and how to fix it.

**Comment by 5T33Z0** [comment]
I had 2 GTX 680 GPUs dying in short succession a couple of years back. Then I just got a Radeon RX 580 and everything has been fine eversince. So there's nothing I can do about that. I would start over with a fesh config. I think the last OS you can install without GPU patches is High Sierra if I am not mistaken

**Comment by rrt225645** [comment]
okey, lets try fresh config then, can you help me setup clover for Sonoma 14.5 ?
im not sure what to choose in the software while installing it and also how to enable pm for my sandy bridge with clover?

**Comment by 5T33Z0** [comment]
No, sorry, I can't do this, This is what support forum and reddit are for.

But for configurtaion guides, you can follow this  guide: https://hackintosh.gitbook.io/r-hackintosh-vanilla-desktop-guide 
For a full documnetation of  Clover (including quirks) you can check my Clover Documentation rpeo: https://github.com/5T33Z0/Clover-Crate/tree/main?tab=readme-ov-file#clover-crate

Good luck

**Comment by rrt225645** [comment]
Okey, thanks for the links and fast reply.
One last question, i love your guides they are so detailed and well explained, cant wait for your guide on gpu and pm for macOS Sequoia but for now, do you have a pm guide for Mojave that works with both opencore and Clover?

**Comment by 5T33Z0** [comment]
PM Guide? You mean CPU Power Managemt? https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/CPU_Power_Management/CPU_Power_Management_(Legacy)#readme

**Comment by rrt225645** [comment]
Yes, CPU Power Management for sandy bridge and Mojave.
I've followed this guide for Sonoma but rechecked it now and i couldnt find something related to older Macos before Monterey like Mojave... also there is nothing mentioned about Clover...
Can you copy pasty the steps that is applicable to Mojave and clover to enable CPU Power Management for sandy bridge and Mojave?

**Comment by rrt225645** [comment]
Btw, how long do you think apple is going to keep Radeon RX Series alive if one consider to build a new hackintosh which i probably should consider since mine is way overdue already and probably cant handle Sequoia if the oc team cut the development for kepler gpu patching :( not to mention CPU Power Management patching from you..

**Comment by 5T33Z0** [comment]
> […] also there is nothing mentioned about Clover […]

That's because the SSDT you generated with ssdtPRGen takes care of the CPU Power Management, so no settings for Clover are needed.

Instructions are in the provided links.
