### ISSUE TITLE
(Perhaps) better way to change the _PRW value (Instant wake fix)

### ISSUE THREAD

**Issue by antoniomcr96** [5T33Z0/OC-Little-Translated#2]
Good morning,
in this section : https://github.com/5T33Z0/OC-Little-Translated/tree/main/04_Fixing_Sleep_and_Wake_Issues/060D_Instant_Wake_Fix/i%20Common%20060D%20Patch
It is suggested to rename 0x6D, 0x03/04 to 0x6D, 0x00 using a patch for those _PRW that are defined as a PackageObj.
It should also work a simple SSDT hotpatch without renames that could be eventually merged with SSDT-GPRW. 
```
DefinitionBlock ("", "SSDT", 2, "OCLT", "GPRW", 0x00000000)
{
    External (_SB_.PCI0.XHC_._PRW, PkgObj) //Pathway of the _PRW of our interest

        If (_OSI ("Darwin"))
        {
            \_SB.PCI0.XHC._PRW [One] = 0x00
        }
       
}
```
Renames such as 0x6D, 0x03/04 to something else can create problems in other parts of the DSDT.

**Comment by 5T33Z0** [comment]
I don't know, since I am not the author of this patch and not really good at AML.  I just translated the Github. But I use these renames and patches on my Laptiop and have no issues with them whatsoever. But I'll try your methd. And if it works I'll add it to the giuide. Thanks for looking into it.

**Comment by dreamwhite** [comment]
This method is way better BUT you'll have to keep track on every single instance of _PRW method that is called. I don't know what are the advantages of doing so...

**Comment by 5T33Z0** [comment]
@antoniomcr96 I tried your method and it works. I've added it to the guide.
