### ISSUE TITLE
[SSDT-AWAC-STA0] Clarifications

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/OC-Little-Translated#22]
Link: https://github.com/5T33Z0/OC-Little-Translated/blob/main/01_Adding_missing_Devices_and_enabling_Features/System_Clock_(SSDT-AWAC)/SSDT-AWAC_STA0.dsl

As per ACPI 6.4. specs, `_STA` is a method, therefore you can't assign it as a local variable. I'd rather delete this SSDT as `STAS` variable patching is way cleaner and compliant.

Same speech with https://github.com/5T33Z0/OC-Little-Translated/blob/main/01_Adding_missing_Devices_and_enabling_Features/System_Clock_(SSDT-RTC0)/SSDT-RTC_STA0F.dsl

**Comment by 5T33Z0** [comment]
Thanks for the info. I will delete the SSDTs if you can provide alternatives. I am not well-versed enough to write them myself.

**Comment by dreamwhite** [comment]
Well, basically there's this approach that every programmer should follow:

- Is the _STA method of that specific device hard-coded or dynamic-coded (like STAS variable)? If it's the first one there's nothing you can do except overriding it with a hot-patch, or recreating the device (See I2C patches that @Baio1977 pushed), otherwise better using the dynamic approach (literally changing a certain variable value, like for OSYS or GPEN/GPHD or STAS)

**Comment by 5T33Z0** [comment]
Okay, then I delete both SSDTs and explanations. Thanks for the eplanations
