### ISSUE TITLE
[AppleALC] List of possible layout-ids

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/OC-Little-Translated#26]
Hi there,
in my spare time I created a GitHub repository containing all the possible layout-ids per codec extracted directly from latest [AppleALC](https://github.com/acidanthera/AppleALC) source.

You can consult it [here](https://github.com/dreamwhite/applealc-layouts).
Let me know your thoughts

**Comment by 5T33Z0** [comment]
Thanks. But I think it's much easier to just use the search funtion in the plist to look for existing Layouts for Laptops for example.

**Comment by dreamwhite** [comment]
> Thanks. But I think it's much easier to just use the search funtion in the plist to look for existing Layouts for Laptops for example.

Yeah it is but my approach was rather a "I have this audio codec, what are the possible layout-ids and how are they associated? Is layout 1 suitable for my XYZ build?"
