### ISSUE TITLE
[OpenIntelWireless] How to reduce IntelBluetoothFirmware weight

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/OC-Little-Translated#27]
Hi,
I was a little bit bored today and created a repository that explains how to reduce the weight of IntelBluetoothFirmware (from ~7.2MB to less than 1MB).
I know that it's not that useful, but at least you'll have a slim kext.

For more infos check [my repo](https://github.com/dreamwhite/ChonkyIntelBluetoothFirmware-Build)

**Comment by 5T33Z0** [comment]
Cool. 
I wonder: does this approach work for **AppleALC** and **BrcmFirmwareData** as well? These kexts also contain a lot of Data for a lot of devices.

I would create a new category then called "Slimming Kexts" or something like that.

**Comment by 5T33Z0** [comment]
Can you put the instructions for compiling AppleALC in here as well so I can include it in the guide? I guess Xcode and MacSDK Kernel are required as well for this?

**Comment by dreamwhite** [comment]
> Can you put the instructions for compiling AppleALC in here as well so I can include it in the guide? I guess Xcode and MacSDK Kernel are required as well for this?

Yeah sure, I think I'll firstly finish creating AirportItlwm slimmed kext versions, then I'll go ahead with AppleALC.

For both of them MacKernelSDK is required, while just in AppleALC it's required also Lilu.kext (DEBUG).

**Comment by dreamwhite** [comment]
Hi,
I created the guide for [AirportItlwm and itlwm size reducing](https://github.com/dreamwhite/Chonky-itlwm-Build)

**Comment by dreamwhite** [comment]
It's me again 😄 
I added custom AppleALC kexts with a single firmware. Here you are the link: https://github.com/dreamwhite/ChonkyAppleALC-Build

**Comment by 5T33Z0** [comment]
Awesome! Thanks a lot!
