### ISSUE TITLE
SSDT-PNLF and Win boot from Opencore

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#3]
I have tested this change on various Hackintoshes and it works Opencore starts Windows regularly and everything works as it should
SSDT-PNLF GFX0
[Archivio.zip](https://github.com/5T33Z0/OC-Little-Translated/files/6873601/Archivio.zip)

![Schermata 2021-07-25 alle 11 03 24](https://user-images.githubusercontent.com/59058746/126893711-ed86d2c8-4e04-4bfd-b60b-1aefe11b080f.png)

**Comment by 5T33Z0** [comment]
What's wrong the issue with the Samples inside the OpenCore package???
I've tested your PNLF on Ivy Bridge and since a lot of things are missing which the original has, your PNLF doesn't reach max brightness on my screen in macOS. I am not going to add this to repo.

**Comment by Baio1977** [comment]
If you can try these PNLF SSDTs only as a test on your HW
TEST N1
[SSDT-PNLF-SNB_IVY.aml.zip](https://github.com/5T33Z0/OC-Little-Translated/files/6873909/SSDT-PNLF-SNB_IVY.aml.zip)

Test N2
[SSDT-PNLF All.zip](https://github.com/5T33Z0/OC-Little-Translated/files/6873917/SSDT-PNLF.All.zip)
 
no need for Rename in config GFX0 to IGPU

![Schermata 2021-07-25 alle 15 00 52](https://user-images.githubusercontent.com/59058746/126899932-43d06ea2-c7eb-4f4a-ba44-a4874dd7db5a.png)

Thanks for all

**Comment by Lorys89** [comment]
> What's wrong the with the Samples inside the OpenCore package???
> I've tested your PNLF on Ivy Bridge and since a lot of things are missing which the original has, your PNLF doesn't reach max brightness on my screen in macOS. I am not going to add this to repo.

test this 
[SSDT-PNLF.dsl.zip](https://github.com/5T33Z0/OC-Little-Translated/files/6892493/SSDT-PNLF.dsl.zip)

**Comment by 5T33Z0** [comment]
This is the exact same file which is included in the OpenCore Package Sample files. Stop sending files please. Thank you.
