### ISSUE TITLE
[L_ALC_Layout-ID] Monterey 12.4 issues

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/OC-Little-Translated#34]
As Monterey 12.3 dropped Python2 pre-built binaries, users need to download Python 2.7.18 installer. [Official download link](https://www.python.org/downloads/release/python-2718/)

**Comment by 5T33Z0** [comment]
So it can run python 2, you only have to install it?

**Comment by dreamwhite** [comment]
> So it can run python 2, you only have to install it?

Yes, eventually you need to link `python2` binary on `/usr/bin/python`, or if you want you can just replace the she-bang in `codecgraph.py` with `/usr/local/bin/python2` (after installing `Python2.pkg` file) and it works :)

**Comment by dreamwhite** [comment]
I have no clue, especially since I think it overrides the existing `python` symlink

**Comment by 5T33Z0** [comment]
Since a python 3 compatible codecgraph version exists, I just link to this. Less headaches for me.
