### ISSUE TITLE
Help: To find out Internal Mic nodes

### ISSUE THREAD

**Issue by plsh2me** [5T33Z0/OC-Little-Translated#36]
Hi, Can you please help me to find the internal mic nodes. 
Speaker, Headphone and Ext. input seems OK, but no int. mic.
I have attached the output and the codec dump, please suggest me the possible solutions.
Thank you
[output.zip](https://github.com/5T33Z0/OC-Little-Translated/files/8840949/output.zip)

**Comment by 5T33Z0** [comment]
There's no Pin Complex Node for an Internal Mic in this schematic.

7, 8, 9 are inputs, but only as Line-In.

8 - 35 - 25 = Mic via Jack, but not internal

You hav to try all the Nodes which can be IN and can be attached to either 7, 8 or 9

**Comment by plsh2me** [comment]
Yes, you are right.
8-35-25 =Mic via jack. 
Rather than this which could be the possible IN. Cause I don't see any IN nodes in the schematic.

**Comment by 5T33Z0** [comment]
Analyze the dumpdec.txt.

19, 18, 26 can also be IN.

Maybe it's one of these codecs which require additional data: https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients: https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients
