### ISSUE TITLE
Simple question about AMD Radeon Pro W6400

### ISSUE THREAD

**Issue by chris1111** [5T33Z0/OC-Little-Translated#39]
Do you think [your guide](https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/AMD_Radeon_Tweaks) works for this Graphica card [AMD Radeon Pro W6400](https://www.amd.com/en/products/professional-graphics/amd-radeon-pro-w6400)

Its a card base `AMD RDNA2`  Architecture,  It is `Navi 24 XL` not 21 or 23

Thanks for the guide

**Comment by 5T33Z0** [comment]
I don't know, really @Baio1977  wrote that SSDT-NAVI.aml and the instructions. Maybe he knows more.

**Comment by chris1111** [comment]
Thanks @5T33Z0 

I would like to order it for my HP Prodesk 600 G1, I already have a Visiontek Radeon RX 560 which works perfectly in Ventura 13 but I would very much like to know if this card works it would be great for low profile graphics card based PC users 😁

**Comment by dakanji** [comment]
> I don't know, really @Baio1977 wrote that SSDT-NAVI.aml and the instructions.

`SSDT-NAVI` is referenced in the instructions but seem to have been removed from the repo.
Is there an issue with it? I found the link to it in archived page but wondering why it was removed.

**Comment by 5T33Z0** [comment]
It's not removed. Look in the Graphics Section. This repo has a TOC and even more TOCs in sub sections. It's not hard to find.

**Comment by dakanji** [comment]
Thanks. I did found after looking long and hard at the TOC.
