### ISSUE TITLE
Add Patch AC Adapter for Laptop

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#4]
I have been following your work for some time and I would like to suggest some changes:

https://github.com/Baio1977/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/AC%20Adapter%20FIX%20(SSDT-AC%5CAC0%5CADP0%5CADP1%5CACAD)

you can improve the information I add

Original Patch in Maciasl by RM

![Schermata 2021-11-01 alle 12 21 42](https://user-images.githubusercontent.com/59058746/139664011-f65924bd-8d45-4393-9ed5-89cae976d7ba.png)

**Comment by 5T33Z0** [comment]
Hi. Thanks for your message. I will incorporate your fix in the repo.

**Comment by Baio1977** [comment]
Read these READMEs, I have added more accurate information, for a correct use of these FIX :

https://github.com/Baio1977/OC-Little-Translated/blob/main/01_Adding_missing_Devices_and_enabling_Features/NVRAM_Fix_(SSDT-PMCR)/README.md

https://github.com/Baio1977/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/Platform_Power_Management_(SSDT-PPMC)

**Comment by 5T33Z0** [comment]
Thanks, I will look into it and update the documents.
