### ISSUE TITLE
[Docs Request] Unified SSDT guide

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/OC-Little-Translated#40]
Given that it's pretty useless and counter-productive when debugging, it would be nice to write a small guide that explains how to write a unified SSDT once you're done with your ACPI.

I'll try summing up things:

- first of all create a folder where you'll make your tests
- for each SSDT disassemble it in `.dsl` and remove `DefinitionBlock` (e.g. `iasl SSDT*.aml`)
- create a dummy SSDT that contains the following code:

```
DefinitionBlock("", "SSDT", 2, "AUTHOR", "HACKSSDT", 0)
{
    #include "SSDT-X.dsl"
    ...

}
```
- compile using `iasl SSDT-FINAL.dsl` and make sure you're not having errors

Make sure to change `AUTHOR` and `HACKSSDT` with your favourite names as well as adding an `#include "SSDT-Y.dsl"` directive for each SSDT. See the below example:

1. folder with disassembled SSDTs

![image](https://user-images.githubusercontent.com/17933708/175834959-d648b4c4-78fb-447d-b21f-0ffbe1bf56b5.png)

2. removed `DefinitionBlock` for each SSDT. e.g.

![image](https://user-images.githubusercontent.com/17933708/175834986-e2313602-8eac-47a9-81cf-cee4c59bc648.png)

3. SSDT with final stuff

![image](https://user-images.githubusercontent.com/17933708/175834996-f1f84278-13b2-424e-82cc-4047a926cd2b.png)

##### Please note that in case you're having issue like `Existing object has invalid type for Scope operator (_SB.PCI0 [Untyped])` add as an external reference in the final SSDT `External (_SB.PCI0, DeviceObj)` like below:

![image](https://user-images.githubusercontent.com/17933708/175835061-62b88be2-1d3c-4f51-941e-92540450d7f1.png)

**Comment by 5T33Z0** [comment]
Not a fan of unifiying SSDTs into one file. Because this way you can't disable single patches –  it's either _all_ or _none_. You can do this on your fork, I won't support thist here.

Also, Olarila mis-uses this method to sneek in devices which re-brand the "About this Mac section".

**Comment by dreamwhite** [comment]
> Not a fan of unifiying SSDTs into one file. Because this way you can't disable single patches – it's either _all_ or _none_. You can do this on your fork, I won't support thist here.

That's not a prob for me. Neither do I support this kind of approach, but something like a disclaimer in such cases may be helpful (e.g. "Just use this method once you're done with ACPI patching" or whatever). In any case up to your choice ditching or not, I won't get mad haha


> Also, Olarila mis-uses this method to sneek in devices which re-brand the "About this Mac section".

Craprila actually does dogshit work with ACPI. Better not throwing them other insults, they're full of them ahha and hated by any person that has a minimum IQ

**Comment by 5T33Z0** [comment]
zsh: command not found: iasl

Ditchig this guide since it requires installing iasl in usr/bin which requires write-enabling the system partition on macOS Catalina and newer, showing hidden files etc.

**Comment by 5T33Z0** [comment]
Using the SSDT-HPET generated by SSDTTime results in compiling errors:

SSDT-HPET.dsl     25:     Name (\_SB.PCI0.LPC.HPET._CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
Error    6074 -         Name already exists in scope ^  (\_SB.PCI0.LPC.HPET._CRS)

    Original name creation/declaration below: (\_SB.PCI0.LPC.HPET._CRS)
    SSDT-HPET.dsl     25:     Name (\_SB.PCI0.LPC.HPET._CRS, ResourceTemplate ()  // _CRS: Current Resource Settings

SSDT-PNLF.dsl     95:                 Method (_INI, 0, NotSerialized)  // _INI: Initialize
Warning  3115 -                                 ^ Not all control paths return a value (\_SB.PCI0.IGPU.PNLF._INI)

ASL Input:     SSDT-ALL.dsl -     544 bytes    316 keywords     21 source lines

Compilation failed. 1 Errors, 1 Warnings, 0 Remarks
No AML files were generated due to compiler error(s)
5t33z0@MacBook-Pro ACPI %

**Comment by dreamwhite** [comment]
> Using the SSDT-HPET generated by SSDTTime results in compiling errors:
> 
> SSDT-HPET.dsl 25: Name (_SB.PCI0.LPC.HPET._CRS, ResourceTemplate () // _CRS: Current Resource Settings Error 6074 - Name already exists in scope ^ (_SB.PCI0.LPC.HPET._CRS)
> 
> Original name creation/declaration below: (_SB.PCI0.LPC.HPET._CRS) SSDT-HPET.dsl 25: Name (_SB.PCI0.LPC.HPET._CRS, ResourceTemplate () // _CRS: Current Resource Settings
> 
> SSDT-PNLF.dsl 95: Method (_INI, 0, NotSerialized) // _INI: Initialize Warning 3115 - ^ Not all control paths return a value (_SB.PCI0.IGPU.PNLF._INI)
> 
> ASL Input: SSDT-ALL.dsl - 544 bytes 316 keywords 21 source lines
> 
> Compilation failed. 1 Errors, 1 Warnings, 0 Remarks No AML files were generated due to compiler error(s) 5t33z0@MacBook-Pro ACPI %

can you send me your ACPI folder as well as the unified dsl file?

**Comment by dreamwhite** [comment]
Alright. I have a question: what happens if you disable `HPET` device like I did [here](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/Docs/ACPI/SSDT-HPET-DISABLE.md)?

**Comment by dreamwhite** [comment]
Oh wait, I found out why you're having problems: you added twice `SSDT-HPET.dsl`. 
Here you are the fixed SSDT: [ACPI_T530.zip](https://github.com/5T33Z0/OC-Little-Translated/files/8991110/ACPI_T530.zip)

**Comment by 5T33Z0** [comment]
Thanks. I tested the resulting SSDT. The system boots noticeably slower than using individual SSDTs. 

Ditching this for real now. Sorry.

**Comment by dreamwhite** [comment]
> Thanks. I tested the resulting SSDT. The system boots noticeably slower than using individual SSDTs.
> 
> Ditching this for real now. Sorry.

ouch! I haven't noticed yet any difference but way better ditching for now... Sorry if I lost time for this haha but still worth it learning new stuff

**Comment by 5T33Z0** [comment]
Maybe it boots faster if you re-organize the structure of the entries so the hierarchy is correct, but this takes forever. And it's pretty much guarenteed that novice users will eff this up.

**Comment by dreamwhite** [comment]
> Done: https://github.com/5T33Z0/OC-Little-Translated/blob/main/N_SSDT-ALL/README.md

Thank you so much. In case you wanna debug the slower boot times maybe we can discuss about it later on Discord (`dreamwhite#0362` is my tag)
