### ISSUE TITLE
[Correction] I225-V guide

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/OC-Little-Translated#41]
Link: https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/Intel_I225-V_Fix_(SSDT-I225V)#user-content-fnref-3-52460499954034579036b340dcb4d433=

Issue: ```Combining Vt-D and DisableIOMapper makes no sense to me but that's what the user reported as working.```

In case you need VT-d features on other OSs (e.g. Linux with KVM), it absolutely makes sense enabling both VT-d and DisableIOMapper

**Comment by 5T33Z0** [comment]
But this section and this table is about enabling the I225 in macOS and not about using VtD in other OSes

**Comment by dreamwhite** [comment]
> But this section and this table is about enabling the I225 in macOS and not about using VtD in other OSes

A disclaimer in such cases may be helpful. As far as I noticed, many people actually boot other OSs using OpenCore (literally worst choice ever but everyone is responsible for their actions) so... Your speech is right for those who only boot macOS via OpenCore and not other OSs
