### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by james090500** [5T33Z0/OC-Little-Translated#42]
Hi,

After trying to apply a new Layout ID 18 for ALC 280 I am getting a Kernel Panic. I am able to successfully build and use a vanilla version of AppleALC, but with my changes it goes wrong. Do you have any ideas?

https://github.com/acidanthera/AppleALC/compare/master...james090500:AppleALC:master

**Comment by 5T33Z0** [comment]
No idea. Never had this issue. There nust be an error somewhere in your Layout-ID.

**Comment by james090500** [comment]
If you think that's the likely problem I will go through again, thank you.

**Comment by james090500** [comment]
As an update. If I remove the configuration from PinConfigs > info.plist it doesn't panic... will see if thats wrong

**Comment by james090500** [comment]
This was resolved. When duplicating an entry in `Resources/PinConfigs.kext/Contents/Info.plist`
xcode changes the CodecID to <real> instead of <integer>

**Comment by 5T33Z0** [comment]
Don't use a plist editor when working with this file. It messes the whole file up. Use VS Studio instead
