### ISSUE TITLE
How to disable an M2 NVMe drive from appearing in macOS?

### ISSUE THREAD

**Issue by danieldeicide** [5T33Z0/OC-Little-Translated#45]
Hello!

Is there a possibility to disable a specific M.2 slot? I am assuming I should be using a custom SSDT (but don't know how)

**Comment by 5T33Z0** [comment]
See chapters 1 and 2. 

You need to find the PCI path of the device in th DSDT. If it contains the method _STA you can disable it pretty easy via SSDT.

I suggest asking for help on a Hackintosh forum or on reddit.
