### ISSUE TITLE
[Proposal] Adding kext compatibility charts

### ISSUE THREAD

**Issue by ColdyMercury** [5T33Z0/OC-Little-Translated#47]
URL: https://github.com/5T33Z0/OC-Little-Translated/tree/main/E_Compatibility_Charts

On this [repo](https://github.com/utopia-team/kexts-description/) there's a work-in-progress list of compatible PCI IDs organized in dedicated .md files for each kext that may attach to certain PCI IDs (e.g. AirportItlwm, IntelMausi ecc)

**Comment by 5T33Z0** [comment]
Thanks for your suggetsion. But all the necessary info about supported models is listed on the respective kext repos already.
