### ISSUE TITLE
SSDT-ALL Suggestion

### ISSUE THREAD

**Issue by rafale77** [5T33Z0/OC-Little-Translated#48]
Not an issue, merely a report/suggestion:

After combining all my DSDT, I noticed that there was significant room for further improvements by reordering and cleaning up the various patches so they go down in descending order: 

Example below
![Screen Shot 2022-07-25 at 06 57 06](https://user-images.githubusercontent.com/15803952/180794929-7b183da9-c6ef-4661-b2ff-23b2b755a605.png)

And therefore streamlining the execution, reduces the size of the file and eliminating a lot of Scope calls and simplifying device pathing.

**Comment by 5T33Z0** [comment]
I guess you have to change the order of the SSDTs based on their PCI paths so that the merged SSDT is cleaner. 

Let me know if you have come up with a solution. Because I don't know how to make ASL to output a neatly formatted SSDT.

**Comment by rafale77** [comment]
MaciASL allows you to move the entire device block one by one to set the order and the location of each device. That part was easy. I then had to edit the paths in the scope and devices one by one.

**Comment by 5T33Z0** [comment]
Yes, I know. Still, not exactly a "stramlined" appraoch. There's nothing I can do about it. I don't see any options in the ASL commands which could do order the entries. As I said in the article: I don't like this method anyways for all the mentioned reasons.

**Comment by rafale77** [comment]
Understood, I don't know of a better way to do it other than manually which I admit is error prone. That being said, without  this reordering/cascading, the benefit of doing the SSDT-ALL merging is minimal.

**Comment by 5T33Z0** [comment]
The thing is: the SSDT might not look nice, but this doesn't really matter, since it is not simply appended at the end of the DSDT. Instead its _data_ is merged with the respective sections of the DSDT addressed via the scopes and ACPI paths.
