### ISSUE TITLE
Where can I write to you in private ??? Thank you

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#49]
Hello great

**Comment by 5T33Z0** [comment]
Hi. I'm on Discord. Same user name.

**Comment by Baio1977** [comment]
discord tag?

**Comment by 5T33Z0** [comment]
5T33Z0

**Comment by Baio1977** [comment]
Baio77#4809 my tag Discord

**Comment by Siddharth8130** [comment]
Hello @Baio1977 I am in need of acer aspire f5-573g-59v4 EFI for Hackintosh. My specs are i5-7200U 16gb ddr4 2400mhz ram and nvidia 940mx 2gb GDDR5 gpu. 1tb sata ssd. Hope that you would help me sir, Please.
