### ISSUE TITLE
01_Adding_missing_Devices_and_enabling_Features PPMC

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#5]
https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/Platform_Power_Management_(SSDT-PPMC)

Hello I'm back to breaking the boxes, this search section in screen is not correct

![Schermata 2021-11-06 alle 11 07 59](https://user-images.githubusercontent.com/59058746/140605918-7b79d31d-4e57-48d1-a2e8-320d93456e3d.png)

As in your case, the search is at ACPI level, the correct thing is to search IOService in order to see if the device is loaded correctly by the system.Not all devices in ACPI are loaded by the system, also thanks to the choices of SMBios etc. etc.
![Schermata 2021-11-06 alle 11 13 45](https://user-images.githubusercontent.com/59058746/140606031-fc1babf7-8315-4b34-bb3f-cb6a8415553c.png)
So it is correct

Thanks as always and sorry, I try to help you make this guide better

**Comment by 5T33Z0** [comment]
Thanks. I am using PPMC.aml on my Dektop (10th Gen i9, iMac20,2). 

But it seems that it does not load:

![Bildschirmfoto 2021-11-06 um 13 20 33](https://user-images.githubusercontent.com/76865553/140609386-68b420e2-4a06-4c9d-b0fa-a3ea6f5d0adb.png)

I compared with iMac19,1 DSDT and it also has PPMC. I don't know why it's not loading

**Comment by Baio1977** [comment]
On series 300 400 500 it should NOT be used, there is PMCR for that series of MOBO and CPU

**Comment by 5T33Z0** [comment]
Okay! Thanks
