### ISSUE TITLE
SSDT ERROR

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#56]
https://github.com/5T33Z0/OC-Little-Translated/blob/main/04_Fixing_Sleep_and_Wake_Issues/060D_Instant_Wake_Fix/i_Common_060D_Patch/SSDT-XPRW.dsl

"""
If (_OSI ("Darwin")){
"""

it must stand after the Method in this case.

Use standard GPRW or UPRW SSDT.

[SSDT-GPRW.dsl.zip](https://github.com/5T33Z0/OC-Little-Translated/files/9691926/SSDT-GPRW.dsl.zip)

[SSDT-UPRW.dsl.zip](https://github.com/5T33Z0/OC-Little-Translated/files/9691927/SSDT-UPRW.dsl.zip)

**Comment by Baio1977** [comment]
https://github.com/5T33Z0/OC-Little-Translated/blob/main/04_Fixing_Sleep_and_Wake_Issues/060D_Instant_Wake_Fix/i_Common_060D_Patch/SSDT-PRW0.dsl.

SSDT-PRW0 correction 

![Screenshot 2022-10-02 alle 09 20 25](https://user-images.githubusercontent.com/59058746/193442801-1572f6cb-5077-4584-8c59-b6895880aa24.png)

Added

"" "
Scope (\)
"" "

**Comment by 5T33Z0** [comment]
Thanks, I'll add the scope. It has been working fine without it on my Laptop for months now, though.

**Comment by 5T33Z0** [comment]
> https://github.com/5T33Z0/OC-Little-Translated/blob/main/04_Fixing_Sleep_and_Wake_Issues/060D_Instant_Wake_Fix/i_Common_060D_Patch/SSDT-XPRW.dsl
> 
> """ If (_OSI ("Darwin")){ """
> 
> it must stand after the Method in this case.
> 
> Use standard GPRW or UPRW SSDT.
> 
> [SSDT-GPRW.dsl.zip](https://github.com/5T33Z0/OC-Little-Translated/files/9691926/SSDT-GPRW.dsl.zip)
> 
> [SSDT-UPRW.dsl.zip](https://github.com/5T33Z0/OC-Little-Translated/files/9691927/SSDT-UPRW.dsl.zip)

Do you mean, like this:

```asl
DefinitionBlock("", "SSDT", 2, "5T33Z0", "XPRW", 0)
{
    External (XPRW, MethodObj)

Method (GPRW, 2)
    {
        If (_OSI ("Darwin"))
        {
            If (0x6d == Arg0) { Return (Package() { 0x6d, 0, }) }
            If (0x0d == Arg0) { Return (Package() { 0x0d, 0, }) }
            Return (XPRW (Arg0, Arg1))
        }

Method (UPRW, 2)
    {
        If (_OSI ("Darwin"))
        {
            If (0x6d == Arg0) { Return (Package() { 0x6d, 0, }) }
            If (0x0d == Arg0) { Return (Package() { 0x0d, 0, }) }
            Return (XPRW (Arg0, Arg1))
        }
    }
  }
}
```

**Comment by Baio1977** [comment]
> Thanks, I'll add the scope. It has been working fine without it on my Laptop for months now, though.

That you say is correct, see example SSDT-XOSI does not have Scope, so it is automatically inserted under (\), which is the primary Scope.

**Comment by 5T33Z0** [comment]
So I have changed it for no reason now…

After the changes in SSDT-XPRW I get a warning now: "Not all Control paths return a value"

Is that a problem?

**Comment by Baio1977** [comment]
Use this file , do not change this is already okay, the 2 SSDTs are independent it is right to make them available individually
[SSDT-GPRW.dsl.zip](https://github.com/5T33Z0/OC-Little-Translated/files/9693279/SSDT-GPRW.dsl.zip)
[SSDT-UPRW.dsl.zip](https://github.com/5T33Z0/OC-Little-Translated/files/9693280/SSDT-UPRW.dsl.zip)
