### ISSUE TITLE
Can you find the right @0,name for Radeon VII.

### ISSUE THREAD

**Issue by li3p** [5T33Z0/OC-Little-Translated#59]
Hi, I followed a topic on tonymacx86 to come this page,  Thanks for your great job.

I have a Radeon VII 16G graphic card, but dont find its @0,name, could you help me with this?

Thank you so much!

**Comment by 5T33Z0** [comment]
I don't know. Use the PowerPlay Tables to optimze performance instead: https://github.com/5T33Z0/OC-Little-Translated/tree/main/11_Graphics/GPU/AMD_Radeon_Tweaks#method-3-using-powerplay-tables
