### ISSUE TITLE
Compatible with Vega 64?

### ISSUE THREAD

**Issue by NathanR-85** [5T33Z0/OC-Little-Translated#61]
I'm making the SSDT patch but ran into something:

While finding the name and path of my Graphics card in IORegistry Explorer, I see a value but also a bridge, which the guide says to watch out for, and the two Terminal commands return nothing, so there's multiple red flags according to the guide.

My IORegistry: https://ibb.co/P9M8tBm

But I have a Sapphire Vega 64 which is fairly common. Will this SSDT not work?

If it helps, here is the audio device in Hackintool: https://ibb.co/XCrJ6QY

Thanks!

**Comment by 5T33Z0** [comment]
You need SSDT-BRGO as well (or integrate BRG0 device in the SSDT)

https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-BRG0.dsl

**Comment by NathanR-85** [comment]
Hello :) I can put both files in but want to make sure I’m making the SSDT correctly.

**Comment by 5T33Z0** [comment]
Well then merge them both together, check and adjust the ACPI paths (the default of SSDT-BRGO suits your case) and then test it.

**Comment by NathanR-85** [comment]
I don't know how to merge them together or adjust the ACPI path. I sent a screenshot above, so does that mean the ACPI patch is **PEGP@0**?

**Comment by 5T33Z0** [comment]
Like this. Adjust the paths as needed. 

```asl
DefinitionBlock ("", "SSDT", 2, "OCLT", "VEGA", 0x00000000)
{
    External (_SB_.PCI0.PEG0, DeviceObj)
    External (_SB_.PCI0.PEG0.PEGP, DeviceObj)

    Scope (\_SB.PCI0.PEG0)
    {
        Scope (PEGP)
        {
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin"))
                {
                    Return (Zero)
                }
                Else
                {
                    Return (0x0F)
                }
            }
        }

        Device (BRG0)
        {
            Name (_ADR, Zero)  // _ADR: Address
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (Zero)
                }
            }

            Device (EGP0)
            {
                Name (_ADR, Zero)  // _ADR: Address
                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    If (_OSI ("Darwin"))
                    {
                        Return (0x0F)
                    }
                    Else
                    {
                        Return (Zero)
                    }
                }

                Device (EGP1)
                {
                    Name (_ADR, Zero)  // _ADR: Address
                    Device (GFX0)
                    {
                        Name (_ADR, Zero)  // _ADR: Address
                    }
                }
            }
        }
    }
}
```

⚠️ NOTE: the issue section is  for reporting issues and **NOT** for asking for help with personal configuration issues! Ask for help on forums or the hackintosh reddit.
