### ISSUE TITLE
New SSDT-NAVI\VEGA56-64

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#62]
[SSDT-Navi-Vega56\64.aml.zip](https://github.com/5T33Z0/OC-Little-Translated/files/9881531/SSDT-Navi-Vega56.64.aml.zip)
![Screenshot 2022-10-27 alle 18 54 06](https://user-images.githubusercontent.com/59058746/198351860-38645082-2cae-4ffe-af55-bea04ba2bef4.png)

Simplified SSDT so that you have fewer problems in OS.
Studying ACPI and Ioreg real Macs I noticed that Navi and Vega are named as in posted SSDT.
See ImacPro 1.1

**Comment by 5T33Z0** [comment]
Thanks, I'll add it to the GPU section

**Comment by Baio1977** [comment]
Thanks to you for this Hackintosh collection, I like it and find it very useful.
THANK YOU

**Comment by 5T33Z0** [comment]
Done. https://github.com/5T33Z0/OC-Little-Translated/tree/main/11_Graphics/GPU/AMD_Vega
