### ISSUE TITLE
VoodooPS2 Update Notice

### ISSUE THREAD

**Issue by 1Revenger1** [5T33Z0/OC-Little-Translated#65]
An [update for the Synaptics PS2 driver](https://github.com/acidanthera/VoodooPS2/commit/f76cb96f8481fe43fa859539032e195898e01250) was just merged for Acidanthera's VoodooPS2. This changes some of the properties which the driver looks for, and removes the need for the Clickpad/Trackpad SSDTs. These are still somewhat useful if you want to change trackpoint cursor and scroll speed, or want an example of setting properties for VoodooPS2.

Also, [VoodooRMI is a stable driver for these SMBus trackpads.](https://github.com/5T33Z0/OC-Little-Translated/blob/main/05_Laptop-specific_Patches/Trackpad_Patches/ThinkPad_Click_and_TrackPad_Patches/README.md?plain=1#L20) Some older thinkpad trackpads don't support Intertouch (Synaptic's term for operating over SMBus instead of PS/2), in which case VoodooPS2Trackpad is still useful.

**Comment by 5T33Z0** [comment]
Thanks. I inbtegrated the info in the Readme and updated the acpi samples.
