### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by chris1111** [5T33Z0/OC-Little-Translated#75]
Hi @5T33Z0 

Extract AMFIPass-v1.2.1 without installing [OCLP-AMFIPass](https://github.com/dortania/OpenCore-Legacy-Patcher/releases/tag/amfipass-beta-test)

Simple bash script command
[AMFIPass-v1.2.1-Extract.zip](https://github.com/5T33Z0/OC-Little-Translated/files/11607793/AMFIPass-v1.2.1-Extract.zip)

![Screenshot 2023-05-30 at 21 47 58](https://github.com/5T33Z0/OC-Little-Translated/assets/6248794/6d47e026-73a2-4a50-9af9-0e7c1171066b)

![Screenshot 2023-05-30 at 21 53 29](https://github.com/5T33Z0/OC-Little-Translated/assets/6248794/72c64cbb-c6a7-4bbe-af6c-576aab208e41)

![Screenshot 2023-05-30 at 22 03 57](https://github.com/5T33Z0/OC-Little-Translated/assets/6248794/85775adb-9f6c-4b35-b869-4455a062ec82)

- [x] `script command`
```bash
#!/bin/bash
# Extract AMFIPass.kext
# By chris1111
rm -rf $HOME/Desktop/AMFIPass-v1.2.1-RELEASE.zip
# get AMFIPass path
if [ "$2" == "" ]; then

echo -n "Please move to the windows ➤  \OpenCore-Patcher.app\"
Follow by ENTER: "
while [ -z "$AMFIPass" ]; do
read AMFIPass
done
if [ ! -d "$AMFIPass" ]; then echo "$AMFIPass not found"; exit; fi 
else
AMFIPass="$2"
fi
 
# open OSX Installer.app
echo -n password | hdiutil attach -stdinpass -owners on -nobrowse -noverify -mountpoint /tmp/AMFI "$AMFIPass"/Contents/Resources/payloads.dmg

cp -Rp /tmp/AMFI/Kexts/Acidanthera/AMFIPass-v1.2.1-RELEASE.zip $HOME/Desktop
Sleep 1
Umount -f /tmp/AMFI

echo "Done ➤ $HOME/Desktop/AMFIPass-v1.2.1-RELEASE.zip"
```

**Comment by 5T33Z0** [comment]
Wow, that's cool. But I don't know what to do. I don't understand the instruction "Please move to the windows ➤  \OpenCore-Patcher.app\". Can you explain? Thank you.

**Comment by chris1111** [comment]
EDIT
[AMFIPass-v1.2.1-Extract.zip](https://github.com/5T33Z0/OC-Little-Translated/files/11611028/AMFIPass-v1.2.1-Extract.zip)


- [x] `script command`
```bash
#!/bin/bash
# Extract AMFIPass.kext
# By chris1111
rm -rf $HOME/Desktop/AMFIPass-v1.2.1-RELEASE.zip
# get AMFIPass path
if [ "$2" == "" ]; then

echo -n "Please move to terminal window ➤  \ OpenCore-Patcher.app \ 
Followed by ENTER: "

while [ -z "$AMFIPass" ]; do
read AMFIPass
done
if [ ! -d "$AMFIPass" ]; then echo "$AMFIPass not found"; exit; fi 
else
AMFIPass="$2"
fi
 
# open OSX Installer.app
echo -n password | hdiutil attach -stdinpass -owners on -nobrowse -noverify -mountpoint /tmp/AMFI "$AMFIPass"/Contents/Resources/payloads.dmg

cp -Rp /tmp/AMFI/Kexts/Acidanthera/AMFIPass-v1.2.1-RELEASE.zip $HOME/Desktop
Sleep 1
Umount -f /tmp/AMFI

echo "Done ➤ $HOME/Desktop/AMFIPass-v1.2.1-RELEASE.zip"
```
![Screenshot 2023-05-31 at 05 17 04](https://github.com/5T33Z0/OC-Little-Translated/assets/6248794/fc86cd83-d684-4806-9e6e-7ff3c26adbb1)

**Comment by chris1111** [comment]
Hi  @5T33Z0   good morning

I put the script [on a gist](https://gist.github.com/chris1111/781e9324bcd9657af294462c0b3f6582) because its easy to editing.
with this revision we can extract this release and the next ones of `OCLP AMFIPass` because it is not looking for a particular kexts number.
You can edit your command script after testing it if you want.
