### ISSUE TITLE
I2C patches not covered in this reposity

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#8]
I2C Hackintosh: I'm adding two patches widely used in hacks, SSDT-USTP and SSDT-SPED.
I can't find the right information to attach, maybe you can find more info about it.
In some hacks I have had, I have used these patches to get the trackpad working , here (https://github.com/Baio1977/Acer-Aspire-E5-574G) 

Example ACER ACPI DSDT analysis: I look for USTP and it looks like in the picture.
I could define USTP as a kind of Bus Sped for I2C

![Schermata 2021-11-14 alle 09 24 02](https://user-images.githubusercontent.com/59058746/141673472-03b64a87-3818-47fa-933f-b537d1a86903.png)

and here (https://github.com/Baio1977/DELL-Inspiron-5584) 
in these two configurations SSDT-USTP + rename in ACER and on DELL SSDT-SPED is fundamental.

Work added :
I2C Other Fixes
SSDT-I2C0\I2C1_USPT :

When to use it ?? : Laptop from 6th to 10th(CometLake) Gen CPU , after analysis of the ACPI.
In combination with SSDT USTP it modifies the config.plist ACPI-Patch section integrates the Rename :

Find USTP: 55 53 54 50 08 
Replace XSTP: 58 53 54 50 08

SSDT-I2C0\I2C1_SPED : Looking for information. DELL 5584 claims this SSDT, without non-working trackpad.It may happen that you read an error in verbose mode by starting the PC they concern SSCN FMCN this is hard to notice when everything is working fine.

**Comment by 5T33Z0** [comment]
Ok. Why is the SSDT called "US**PT**" when the rename it is related to is "US**TP**"? Or is it a typo?

**Comment by Baio1977** [comment]
I'm posting examples and trying to introduce whatever is in my possession, I will have to contact a GURU I 2C hackintosh most likely

**Comment by Baio1977** [comment]
> Ok. Perché l'SSDT è chiamato "US **PT** " quando il nome a cui è correlato è "US **TP** "? O è un errore di battitura?

My error sorry

**Comment by 5T33Z0** [comment]
Don't you need an "External (XSTP, SomethingObj)", so the SSDT-USTP.aml works?

**Comment by Baio1977** [comment]
Of course it works, I personally use it on [ ](https://github.com/Baio1977/Acer-Aspire-E5-574G)

**Comment by 5T33Z0** [comment]
ok.

**Comment by 5T33Z0** [comment]
I need additional information for SSDT-I2C1_SPED.dsl for the documentation.
What is the patch principle? Is the same as SSDT-USTP or does it use other renames?
What to search for in DSDT?

Thanks.

**Comment by Baio1977** [comment]
![Schermata 2021-11-18 alle 18 05 13](https://user-images.githubusercontent.com/59058746/142462513-33fb567f-7012-4ef3-9e3d-3fdef8abce6a.png)
Example of the information in verbose for the SPED methods for I2C.
Just for completeness post this photo
