### ISSUE TITLE
Graphics don't initalize after OCLP root patch

### ISSUE THREAD

**Issue by mortalkombatlegend92** [5T33Z0/OC-Little-Translated#80]
I followed the guide and added everything besides the amfipass kext since that requires macos to get, I installed Ventura successfully on my Ivy Bridge but after running OCLP and installing the root patch graphics don't initialize upon boot. Here is my config
https://drive.google.com/file/d/1aYWgFfmDa0-e1vwY7n-ENJhMu4gbK9Lf/view?usp=sharing

**Comment by 5T33Z0** [comment]
Which graphics are you referring to:

- iGPU? >> Verify iGPU is enabled in BIOS. Try a different AAPL.ig-platform-id: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-hd-graphics-25004000-ivy-bridge-processors
- dGPU? >> `-wegnoegpu` boot-arg is enabled. 
- SMBIOS>> **iMac13,1** for iGPU use, **iMac13,2** for dGPU (**enable Booter Pactches first!!!!!**)

**Comment by mortalkombatlegend92** [comment]
Yeah I'm trying to get my hd4000 iGPU to work. I tried all of the desktop framebuffers from the github you linked but while those did initialize graphics there was no graphics acceleration and it didn't set the correct resolution for my monitor.
