### ISSUE TITLE
Thinkpad T470S Dual Battery - Please HELP :(

### ISSUE THREAD

**Issue by hoaug-tran** [5T33Z0/OC-Little-Translated#81]
Hi 5T33Z0.

Thank you for your contribution to the community. you are wonderful. Wish you have a good day.

Last month i was install macos on my laptop Lenovo Thinkpad T470S. My Laptop Specs:

- Processor and Chipset: Intel Core i5 6300u
- Graphics: Intel HD 520
- Storage: SN530
- RAM: 12 GB DDR4
- 1 x Synaptics SMBUS Trackpad + Trackpoint
- 1 x PS/2 Keyboard
- 1 x USB 3.0 card reader
- 3 x USB 3.0 type a ports
- 1 x TB3/USB C port
- 1 x HDMI port
- 1 x 3.5mm mic/headphone jack
- Dual Battery

I have researched and learned that my Laptop has 2 batteries and I have learned a bit of ACPI code and patched SSDT-BATC. I use SSDT-BATC included with ECEnabler.kext and Battery works

 

I thought everything was fine but no. I realized that my battery is only taking half its capacity. My battery as far as I know it has ~4k4 mAh but the macos side only receives ~2k mAh. I have searched and patched a lot but the number still only stops at 1k8. With such a battery capacity, I cannot use it without a charger. help me please. I spent a month trying to fix my battery but failed. if not fix my battery is too low and can not be used without charging 24/24. I can't watch youtube (1920x1080) more than 30p, only about ~30p my laptop is out of battery.... i also used kext CPUFriend + CPUFriendFriend (with 800mhz ) because i think its CPU problem but NOT... I'm really helpless right now. please help me...thank you very much

Here is my DSDT and SSDT i use for Battery ( work but with very small capacity )

- i use SSDT-BATX.dsl without patch BAT0,1 to BATX because i just use it for fix battery 16,32 and 128 byte ( i dont use ECEnabler because its make my battery has been reported for maintenance - and still low capacity )
- SSDT-BATC for Notify BAT0 and BAT1 ( i also have rename Patch )
- SSDT-BATT.am. I found it on Oclittle github ( I don't know if it helpful or not )

[DSDT and SSDTs.zip](https://github.com/5T33Z0/OC-Little-Translated/files/12323179/DSDT.and.SSDTs.zip)

And here is my EFI:

https://drive.google.com/file/d/19fNSEdeseKGWO_skEzErd6cl-MeoM6s6/view?usp=drive_link

THANK YOU VERY MUCH

**Comment by 5T33Z0** [comment]
Sorry, but I don't know how to do battery patching. I am using ECEnaber myself and it worked out of the box. But my Laptops don't have dual batteries.

My guess is that only one of your batteries is detected so that only one is charged and therefore you only have half the capacity available. There should be a `BAT0` and `BAT1` in your DSDT you have to work with that. 

Check for patches and the guide linked in the repo: https://github.com/5T33Z0/OC-Little-Translated/tree/main/05_Laptop-specific_Patches/Battery_Patches

Good Luck

**Comment by hoaug-tran** [comment]
@5T33Z0 thank you. i tried your guide about patch battery but it still not working.. i dont know what i need to do right now

**Comment by 5T33Z0** [comment]
It's not my guide. I suggest you look for help in a forum or on OpenCore's discord channel: https://discord.gg/Wxam8aH

**Comment by hoaug-tran** [comment]
thread in insanelymac about it is mine... I also searched for help in the hackintosh community discord but to no avail. There aren't many people who know SSDT well so... I'm really thinking of giving up..

**Comment by 5T33Z0** [comment]
Check this repo: 

https://github.com/Elemiel-K/Opencore-T470s/tree/master 

You will need:

- `SSDT-BATC.aml`
- `SSDT-BATT.aml`
- ACPI Patches from the config (`TP-Bat…` and `BATW to WBAT`)
