### ISSUE TITLE
Sonoma WiFi issues

### ISSUE THREAD

**Issue by kbnomad** [5T33Z0/OC-Little-Translated#83]
OCLP detected Modern Wireless (BCM4360), installed root patches, rebooted.
Wifi/BT shows up now, but when I try to connect to wifi (after inputting password). 
macOS crashes, panic and reboots.

panic(cpu 12 caller 0xffffff801d1878d3): Kernel trap at 0xffffff8020e35fa8, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000160, CR3: 0x0000000021d6c000, CR4: 0x00000000003406e0
RAX: 0x00000000fffffff2, RBX: 0xffffff86a5cdf400, RCX: 0x0000000000002aab, RDX: 0xffffffcc2d7c734c
RSP: 0xffffffcc2d7c7310, RBP: 0xffffffcc2d7c7310, RSI: 0xffffffcc2d7c7687, RDI: 0x0000000000000000
R8:  0xffffffcc2d7c72d8, R9:  0x0000000000000001, R10: 0x0000000000000002, R11: 0x000000000000000b
R12: 0xffffff950abaf000, R13: 0xffffff86a5a7b800, R14: 0xffffff86a5ce8400, R15: 0xffffffcc2d7c7687
RFL: 0x0000000000010246, RIP: 0xffffff8020e35fa8, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000160, Error code: 0x0000000000000000, Fault CPU: 0xc VMM, PL: 0, VF: 1

Panicked task 0xffffff86a5916218: 342 threads: pid 0: kernel_task
Backtrace (CPU 12), panicked thread: 0xffffff86a643c5a8, Frame : Return Address
0xffffffcc2d7c6c90 : 0xffffff801d03a211 
0xffffffcc2d7c6ce0 : 0xffffff801d197ce0 
0xffffffcc2d7c6d20 : 0xffffff801d18742c 
0xffffffcc2d7c6da0 : 0xffffff801cfd6951 
0xffffffcc2d7c6dc0 : 0xffffff801d03a4fd 
0xffffffcc2d7c6eb0 : 0xffffff801d039ba3 
0xffffffcc2d7c6f10 : 0xffffff801d7d91ab 
0xffffffcc2d7c7000 : 0xffffff801d1878d3 
0xffffffcc2d7c7180 : 0xffffff801d1875b7 
0xffffffcc2d7c7200 : 0xffffff801cfd6951 
0xffffffcc2d7c7220 : 0xffffff8020e35fa8 
0xffffffcc2d7c7310 : 0xffffff8020bf102e 
0xffffffcc2d7c76e0 : 0xffffff8020c9a86c 
0xffffffcc2d7c78a0 : 0xffffff8020ca09bc 
0xffffffcc2d7c7950 : 0xffffff8020cc6267 
0xffffffcc2d7c7b00 : 0xffffff8020ca1caa 
0xffffffcc2d7c7b50 : 0xffffff8020bb23d9 
0xffffffcc2d7c7b80 : 0xffffff8020bc07d4 
0xffffffcc2d7c7ca0 : 0xffffff8020bbe488 
0xffffffcc2d7c7d40 : 0xffffff8020bd3813 
0xffffffcc2d7c7da0 : 0xffffff8020a402ec 
0xffffffcc2d7c7de0 : 0xffffff8020a4097d 
0xffffffcc2d7c7e30 : 0xffffff8020a40a3d 
0xffffffcc2d7c7e40 : 0xffffff801d710618 
0xffffffcc2d7c7ea0 : 0xffffff801d093b28 
0xffffffcc2d7c7ee0 : 0xffffff801d094bb8 
0xffffffcc2d7c7fa0 : 0xffffff801cfd619e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[4C07538B-62EB-3D6D-AEF9-93BCDCF45FAB]com.apple.0xffffff8020970000-com.apple.driver.0xffffff8020b56fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[26773101-4F1A-339A-9597-EF2645721A3F]com.apple.0xffffff801e660000-com.apple.driver.0xffffff801e696fff
            dependency: com.apple.driver.corecapture(1.0.4)[0DED4F91-AC29-379C-9A48-83E6009E40F0]com.apple.0xffffff801fb55000-com.apple.driver.0xffffff801fb77fff
            dependency: com.apple.iokit.CoreAnalyticsFamily(1)[4A31F7E7-78EA-39E5-BD87-85AC3D4D3AE4]com.apple.0xffffff801ea3d000-com.apple.driver.0xffffff801ea46fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[7350A38C-B7AE-3627-867C-48504D02BA13]com.apple.0xffffff801f0af000-com.apple.driver.0xffffff801f0c6fff
            dependency: com.apple.iokit.IOSkywalkFamily(1.0)[035A9AD9-6CDE-362F-8DEC-B664BC6431EC]com.apple.0xffffff80208a2000-com.apple.driver.0xffffff8020960fff
            dependency: com.apple.kec.corecrypto(14.0)[9A9FD228-3123-32AE-9761-042B08D57A85]com.apple.0xffffff801fb86000-com.apple.driver.0xffffff801fc01fff
         com.apple.driver.AirPort.BrcmNIC(1400.1.1)[E4678FEB-1DC1-35CC-9306-48021083D04A]com.apple.0xffffff8020b7a000-com.apple.driver.0xffffff80213f1fff
            dependency: com.apple.driver.corecapture(1.0.4)[0DED4F91-AC29-379C-9A48-83E6009E40F0]com.apple.0xffffff801fb55000-com.apple.driver.0xffffff801fb77fff
            dependency: com.apple.driver.mDNSOffloadUserClient(1.0.1b8)[14410048-29B3-3126-BE24-D2A0BD5DFE52]com.apple.0xffffff801f309000-com.apple.driver.0xffffff801f30dfff
            dependency: com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[4C07538B-62EB-3D6D-AEF9-93BCDCF45FAB]com.apple.0xffffff8020970000-com.apple.driver.0xffffff8020b56fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[7350A38C-B7AE-3627-867C-48504D02BA13]com.apple.0xffffff801f0af000-com.apple.driver.0xffffff801f0c6fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[6A0762A3-54A1-3652-932A-99F3B8E3D842]com.apple.0xffffff801f310000-com.apple.driver.0xffffff801f341fff
            dependency: com.apple.iokit.IOSkywalkFamily(1.0)[035A9AD9-6CDE-362F-8DEC-B664BC6431EC]com.apple.0xffffff80208a2000-com.apple.driver.0xffffff8020960fff
[panic-2023-09-09-073334.txt]

(https://github.com/5T33Z0/OC-Little-Translated/files/12565242/panic-2023-09-09-073334.txt)

**Comment by 5T33Z0** [comment]
- Double-Check instructions and config changes
- Make sure to block IOSkywalkFamily kext
- Use latest nightly builds of kext

**Comment by kbnomad** [comment]
Thanks for the reply.
Yes, I've blocked com.apple.iokit.IOSkywalkFamily
Triple-checked instructions and config changes but to no avail.

<img width="1053" alt="image" src="https://github.com/5T33Z0/OC-Little-Translated/assets/95722437/3c126a4e-02c3-4cda-88dc-ea3ace31dc5e">
<img width="1448" alt="image" src="https://github.com/5T33Z0/OC-Little-Translated/assets/95722437/7b3f4baa-54da-4d2b-9d7f-1110e67b6f42">

**Comment by 5T33Z0** [comment]
Could be related to AMFI. Try `-amfipassbeta` boot-arg.

**Comment by kbnomad** [comment]
that is also in the boot-arg.
replaced all kext files again just to make sure and rebooted, still panicking

**Comment by 5T33Z0** [comment]
AmfiPass.kext is missing.

**Comment by kbnomad** [comment]
Forgot to add AMFI; just added it, rebooted and tried connecting the wifi. still panicked.

By the way, thank you for replying.


<img width="1045" alt="Screensh
[panic-2023-09-09-090048.txt](https://github.com/5T33Z0/OC-Little-Translated/files/12565364/panic-2023-09-09-090048.txt)
ot 2023-09-09 at 5 00 30 AM" src="https://github.com/5T33Z0/OC-Little-Translated/assets/95722437/cd18dc50-2c7d-4713-8ec4-90d6a4f8f92e">

**Comment by 5T33Z0** [comment]
Add `-brcmfxbeta` boot-arg and see if this changes anything. If it doesn't I can't help you. I am using this fix successfully on my Laptop.

**Comment by kbnomad** [comment]
> 

I have that one too.. :/

**Comment by 5T33Z0** [comment]
Yes, disable it. The latest version of OCLP manages to detect Wi-FI now.
