### ISSUE TITLE
macOS Sonoma typo correcting

### ISSUE THREAD

**Issue by PGBSean** [5T33Z0/OC-Little-Translated#84]
![image](https://github.com/5T33Z0/OC-Little-Translated/assets/97381104/5269e269-1151-49ce-adbd-773ffacd77d0)
macOS 13 Sonoma ❌
macOS 14 Sonoma ✅

Link: https://github.com/5T33Z0/OC-Little-Translated/tree/main/10_Kexts_Loading_Sequence_Examples#kernel-support-table

**Comment by 5T33Z0** [comment]
Thanks. I fixed the typo.
