### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PGBSean** [5T33Z0/OC-Little-Translated#85]
https://github.com/5T33Z0/OC-Little-Translated/tree/main/D_Updating_OpenCore#for-users-updating-from-opencore-065-or-lower

![image](https://github.com/5T33Z0/OC-Little-Translated/assets/97381104/475d1e26-0976-4928-8e5f-c09480f6a6a1)

Should be "Updating Bootstrap"

**Comment by 5T33Z0** [comment]
Fixed. Thank you.
