### ISSUE TITLE
Trying to get iServices to work

### ISSUE THREAD

**Issue by PGBSean** [5T33Z0/OC-Little-Translated#86]
![image](https://github.com/5T33Z0/OC-Little-Translated/assets/97381104/df606ada-f7b3-4e3e-89f3-eece2e715220)

Currently, my machine only has 2 network adapters:
+ Marvell AVASTAR 88W8897 Wi-Fi card
+ HoRNDIS.kext for Android tethering

In the picture, you can see that only the USB (HoRNDIS) is shown in the list, with en0 marked as not built-in.

I have tried to make HoRNDIS built-in, iServices does not work however. I have also tried to make the incompatible Wi-Fi card as built-in, does not work either.

Is there any _patches_ I can do to make iServices work?

**Comment by 5T33Z0** [comment]
Refer to [Fixing iServices](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html) chapter of OpenCore Install Guide
