### ISSUE TITLE
Fix Typo again

### ISSUE THREAD

**Issue by PGBSean** [5T33Z0/OC-Little-Translated#90]
In the Config Tips & Tricks folder, in the Disabing SIP section, there is a line:
"This deletes the current csr value from the NVRAM on reboot and replaces it with the value stored under "NVRAM > Add…". This is **_Very_** useful if you have different macOS installs which use different CSR values."
Change the word from "Very" to "very"

**Comment by 5T33Z0** [comment]
Thanks. Fixed (and improved).
