### ISSUE TITLE
Broken link(?) on modern macOS

### ISSUE THREAD

**Issue by pgbsean** [5T33Z0/OC-Little-Translated#91]
In directory Graphics > Inject EDID, you mentioned about the application FixEDID, unfortunately it has been broken on modern macOS due to it's being a 32-bit app.

Solution is to find a fork that contains the 64-bit build or an alternative application.

**Comment by 5T33Z0** [comment]
If you read the istructions of my guide carefully, it tells you exactly where in the folder structure the executable 64 bit binary lives!

So: nothig is broken, nothing to fix!

**Comment by 5T33Z0** [comment]
I would try the right-click menu or disabling Gatekeeper.

![Bildschirmfoto 2023-12-04 um 07 28 13](https://github.com/5T33Z0/OC-Little-Translated/assets/76865553/c141dff0-3729-4844-823a-0b8bdaeba26b)
