### ISSUE TITLE
Fixing "foggy" discoloration

### ISSUE THREAD

**Issue by PGBSean** [5T33Z0/OC-Little-Translated#97]
![PXL_20231219_022550007.jpg](https://github.com/5T33Z0/OC-Little-Translated/assets/97381104/0b44d10d-e132-48f6-8205-c2c38a97b0f5)

This is the Surface Pro 1, which runs Intel Core i5 Ivy Bridge. Currently it is suffering from this weird foggy white color overlay.

I have tried many fixes from your repository (device-id, EDID patches, etc.) and the official OpenCore Post-Install guide, but it doesn't resolve my discoloration.

Are there any ways I can fix my build?

**Comment by 5T33Z0** [comment]
I don't know. Did you have a look at the section for adjusting the OC config for running macOS 12 or newer on Ivy Bridge already?
https://github.com/5T33Z0/OC-Little-Translated/blob/main/14_OCLP_Wintel/Guides/Ivy_Bridge.md

**Comment by PGBSean** [comment]
I did look at that section before, didn't work neither.

**Comment by 5T33Z0** [comment]
Okay. Since this Repo is not aimed at providing support for fixing individual devices, I suggest you consult a help forum or the official OpenCore discord channel for help

19.12.2023 13:51:36 sean.pgb ***@***.***>:
