### ISSUE TITLE
Broken link to Jacksonhacks SPPT example files

### ISSUE THREAD

**Issue by perez987** [5T33Z0/OC-Little-Translated#99]
Dear friend, the link to example files by Jasonkacks with explanations of the PowerPlayInfo table code seems to be broken.

This repo is a very very big work, continually growing and offering more and more information. Thank you.

![Jasonhacks](https://github.com/5T33Z0/OC-Little-Translated/assets/50429399/7a6174cb-9c49-4e93-af98-7efa62d97a2b)

**Comment by 5T33Z0** [comment]
Thanks for the info. The link is fixed.
